import type { Instrument, Signal } from '../src/exchange/bybit/types.js';
export const instrument: Instrument = {
  symbol: 'BTCUSDT',
  tickSize: '0.5',
  qtyStep: '0.1',
  minOrderQty: '0.1',
  maxOrderQty: '100',
  maxMarketOrderQty: '100',
  minNotional: '5',
  maxLeverage: 3,
};
export const signal: Signal = {
  id: 's',
  symbol: 'BTCUSDT',
  timestamp: 1000,
  candleStart: 0,
  side: 'Long',
  entry: 100,
  stopLoss: 95,
  takeProfit: 110,
  score: 80,
  decision: 'accepted',
  reasons: ['trend confirmed'],
  rejections: [],
  snapshot: {
    price: 100,
    ema9: 100,
    ema21: 99,
    ema50: 98,
    rsi: 55,
    atr: 4,
    vwap: 99,
    volume: 100,
    volumeAverage: 90,
    spread: 1,
    imbalance: 2,
    trendEma21: 100,
    trendEma50: 99,
  },
};
